### ISSUE TITLE
Gimana cara buat bot 24 jam . How to make bot active 24 hours.

### ISSUE THREAD

**Issue by fadhil050804** [YogaSakti/imageToSticker#108]
Gimana cara buat bot 24 jam. plis kasih tau. soalnya aku suka banget sama program anda, dari padang sumatera barat.

How do I create a 24 hour bot. please tell me because I really like your program, from Padang, West Sumatra.

**Comment by benirabbny** [comment]
pake rdp vps

**Comment by fadhil050804** [comment]
> pake rdp vps

kalo ga bisa konek ke rdp gimana. gw udah ada akun rdp nya

**Comment by fadhil050804** [comment]
tunjukin. kalau heroku itu fungsinya apa??

**Comment by benirabbny** [comment]
> > pake rdp vps
> 
> kalo ga bisa konek ke rdp gimana. gw udah ada akun rdp nya

bisa harusnya

**Comment by restugbk** [comment]
mampir https://api.i-tech.id/
