### ISSUE TITLE
Gimana cara nambah fitur?

### ISSUE THREAD

**Issue by fadhil050804** [YogaSakti/imageToSticker#111]
gimana cara nambah fitur ya?? biar banyak gtu. tolong kasih tau. saya masih SMA kelas 1. baru masuk ke pemrograman otodidak.
dan ga ngerti node js, python, dan semacamnya
. mohon dibantu

**Comment by Nurutomo** [comment]
ke `./message/handler/index.js`
tambahin ini didalam kurung `switch () {}` sebelum `default:`
```js
case 'commnad':
  // TODO: taruh kode kamu disini
  break
```

**Comment by restugbk** [comment]
mampir https://api.i-tech.id/

**Comment by fadhil050804** [comment]
Contohkan 1 bang. gak ngerti aku cara nulisnya. mohon dibantu bang

**Comment by Nurutomo** [comment]
> Contohkan 1 bang. gak ngerti aku cara nulisnya. mohon dibantu bang

```js
case 'commnad':
  // Jika ada pesan'#command' nanti bot akan balas dengan teks 'Ini contohnya'
  client.sendText(from, 'Ini contohnya')
  break
```

**Comment by daenghunter** [comment]
@Nurutomo masih gapaham dia, contohin bang :v

**Comment by YogaSakti** [comment]
Belajar dulu javascript, abis itu belajar OOP, terus belajar node.js

**Comment by Nurutomo** [comment]
> @Nurutomo masih gapaham dia, contohin bang :v

BIngung kalo dijelasin, mending langsung code nya aja:v
![image](https://user-images.githubusercontent.com/18616827/99027253-5ae64400-259f-11eb-88b1-c980cce67ef9.png)

**Comment by fadhil050804** [comment]
> Belajar dulu javascript, abis itu belajar OOP, terus belajar node.js

makasih bg. kek nya harus belajar dari akar
ga bisa loncat
