### ISSUE TITLE
problem with ig / twitter downloader

### ISSUE THREAD

**Issue by kazuRW** [YogaSakti/imageToSticker#12]
just can send url ? not video like tiktok?

sorry 

and the throuble is can't visite link if #ig url showed

**Comment by YogaSakti** [comment]
I don't want to take risks that will make the bot work hard and become slow

**Comment by kazuRW** [comment]
but the url of #ig result is showed "bad url" , can't download

Pada tanggal Kam, 6 Agt 2020 23.24, Imperial Owl <notifications@github.com>
menulis:

**Comment by YogaSakti** [comment]
try the last update

**Comment by YogaSakti** [comment]
Twitter downloader harusnya udah bisa, kalo Instagram belom nemu solusi.

**Comment by kazuRW** [comment]
yeah , twitter downloader is very working , but instagram is just show bitly url, go do the same as twitter video downloader sir, thank you for your work ^_^
