### ISSUE TITLE
cara supaya bot tidak say hi ke semua anggota group WA gimana?

### ISSUE THREAD

**Issue by fadhil050804** [YogaSakti/imageToSticker#132]
cara supaya bot tidak say hi ke semua anggota group WA gimana?
spam kali soalnya. 
plis tolongin

**Comment by juwenaja** [comment]
maksut?

**Comment by FaizBastomi** [comment]
> cara supaya bot tidak say hi ke semua anggota group WA gimana?
> spam kali soalnya.
> plis tolongin

gimana tuh maksudnya?🤔

**Comment by sukrosono** [comment]
coba tanya togok

**Comment by FaizBastomi** [comment]
@fadhil050804 jika tidak ada kelanjutannya
mohon issue ini ditutup

terima kasih atas perhatiannya 😊
