### ISSUE TITLE
Eror code

### ISSUE THREAD

**Issue by Fakhri17** [YogaSakti/imageToSticker#16]
TypeError: Cannot read property 'trim' of undefined

**Comment by kazuRW** [comment]
yes msghandler js 57/27 is problem but the features is still working :)

**Comment by YogaSakti** [comment]
Kayaknya gara2 pesan suara deh, nanti gw cek lagi. Oh ya ini udah pake update terakhir belom?

**Comment by Fakhri17** [comment]
Belum. Habis ini kucek


Pada tanggal Rab, 12 Agt 2020 01.50, Imperial Owl <notifications@github.com>
menulis:
