### ISSUE TITLE
qr code isn't displayed properly 

### ISSUE THREAD

**Issue by purple92836** [YogaSakti/imageToSticker#23]
When i try to start the bot, it doesn't show qr code, just a random set of letters, did i do something wrong?
![IMG_20200815_142158](https://user-images.githubusercontent.com/69710597/90307691-daae3500-df02-11ea-97e0-125fea814f2b.jpg)

**Comment by rebahanelite** [comment]
don't use the command "npm start"
try using "node index.js" when starting up in git bash
if there are still problems, wait for the developer to find a solution

**Comment by purple92836** [comment]
Thank you! after using "node index.js" command, the qr code now shows correctly.
