### ISSUE TITLE
Gini bang maksud saya, jadi pas mau ngeforward kgk bisa

### ISSUE THREAD

**Issue by JuwenAjaa** [YogaSakti/imageToSticker#27]
![Screenshot_20200816_153920](https://user-images.githubusercontent.com/69716593/90330523-7a3cf780-dfd7-11ea-8eda-69efed3327aa.jpg)

**Comment by YogaSakti** [comment]
![IMG_20200816_165734](https://user-images.githubusercontent.com/24309806/90331808-af4e4780-dfe1-11ea-8fff-785e5f36b3a5.jpg)

Di gw lancar2 aja kok, error gimana dah

**Comment by JuwenAjaa** [comment]
Coba banv, kirim file Botnya ulang please

**Comment by YogaSakti** [comment]
hah?

**Comment by YogaSakti** [comment]
itu tinggal clone/download lagi

**Comment by JuwenAjaa** [comment]
Gw udah install ulang 5 kali, cuman gak ada perubahan. Terus gw juga udh update

**Comment by YogaSakti** [comment]
lah di laptop gw gada masalah kok

**Comment by JuwenAjaa** [comment]
![Screenshot_20200816_171515](https://user-images.githubusercontent.com/69716593/90332084-21c02700-dfe4-11ea-9b0f-5817e84fb4ea.jpg)

Nah iya bang, gw juga bingung nih. Apa ada yg harus di dedit lagi kah index.js nya?

**Comment by YogaSakti** [comment]
gada yang harus di edit, gada msalah di fitur sticker

**Comment by JuwenAjaa** [comment]
Pake wa bisnis masalah kah?

**Comment by YogaSakti** [comment]
coba aja pake wa biasa

**Comment by JuwenAjaa** [comment]
Oke gw Cob dulu

**Comment by dandyraka** [comment]
> gada yang harus di edit, gada msalah di fitur sticker

Lah benerin lah bang, gimana sih

**Comment by YogaSakti** [comment]
> > gada yang harus di edit, gada msalah di fitur sticker
> 
> Lah benerin lah bang, gimana sih

diam ngab

**Comment by kazuRW** [comment]
di aing lancar" aja brok
