### ISSUE TITLE
cara atasin lag?

### ISSUE THREAD

**Issue by fnbots-wa** [YogaSakti/imageToSticker#37]
bang, gimana caranya ngatasin lag parah setelah beberapa waktu ngerun? contoh kalo abis buat ambil stiker / kirim gambar / video, tiba² aja lag parah. ngga tau kenapa, tapi untuk sendmedia aja lag nya, kalo sendtext masih lancar. tapi itu lag nya parah sampe harus reboot vps dulu bang. ada pencerahan?

**Comment by dandyraka** [comment]
Untuk media kan dia ga file, alias string base64 yg super banyak. Kemungkinan itu yang bikin berat, saran coba upgrade aja spek vps nya.

**Comment by mikuuu-chan** [comment]
pake spek 8gb ram 4core bang, tetep aja lag.

**Comment by dandyraka** [comment]
Lag nya itu gimana?

**Comment by mikuuu-chan** [comment]
kayak pas lagi command ambil media, stiker, lagu, video, image, command yang pakai api. dalam kurun beberapa waktu, lalu ngelag banget, apalagi kalo ada error, langsung stuck, harus direboot vps nya dulu baru bisa jalan lagi. kalo cuman kill screen tetep ngelag. tapi ini cuman untuk selain kirim text. padahal kirim video&image&audio pakenya sendfile path, bukan url

**Comment by YogaSakti** [comment]
belom ngalamin yang kayak gini, aneh banget kalo sampe harus reboot vps segala. kirim file kekgitu kan emang berat uploadnya

**Comment by mikuuu-chan** [comment]
gimana ya cara fixnya... aneh banget :(

**Comment by ppabcd** [comment]
Kalau itu tergantung koneksi dari hp sama di servernya sih. Setaku kalau ngirim media itu kan dari web whatsapp ke hp dulu baru ke penerima pesan. Jadi koneksi & device hp juga mempengaruhi dan juga kalau misalkan beberapa chat proses pengiriman, chat lainnya jadi kepending dan bikin antrian yang lumayan banyak.

**Comment by mikuuu-chan** [comment]
iya masalahnya diserver kadang juga malah stuck, mau diakalin gimanapun tetep aja numpuk request kalo udah terlanjur delay

**Comment by maderio** [comment]
delay convert image ke sticker kah?

**Comment by mikuuu-chan** [comment]
semua media, gak cuman sticker

**Comment by maderio** [comment]
coba pake golang bang

**Comment by fnbots-wa** [comment]
masih penasaran sama js, rio

**Comment by YogaSakti** [comment]
Kalo urusan media ya mungkin speed upload servernya sih.

**Comment by fnbots-wa** [comment]
ente pake server region apa bro?? udak tak whois, coba pake server us, atau server jp, server indo, sama server sgp, sama aja. udah coba pake proxy juga.

**Comment by maderio** [comment]
> masih penasaran sama js, rio

lah, ini meka?

**Comment by fnbots-wa** [comment]
@maderio kenapa?

**Comment by maderio** [comment]
> @maderio kenapa?

@fnbots-wa bagi wa u

**Comment by fnbots-wa** [comment]
> > @maderio kenapa?
> 
> @fnbots-wa bagi wa u

twitter.com/anaknakaal_

**Comment by YogaSakti** [comment]
> ente pake server region apa bro?? udak tak whois, coba pake server us, atau server jp, server indo, sama server sgp, sama aja. udah coba pake proxy juga.

@dandyraka lu pake server region mana?

**Comment by mazrizal-id** [comment]
W pake 1 Core , 1 GB RAM 
Lancar" ae v:

**Comment by fnbots-wa** [comment]
salah struct sc bikin bot delay kadang stuck dan browser close. "kalo bisa diringkas makin baik tanpa banyak pengulangan yang gak diperlukan"
