### ISSUE TITLE
EROR TWITTER DOWNLOADER, TIKTOK DOWNLOADER

### ISSUE THREAD

**Issue by MSI0072** [YogaSakti/imageToSticker#41]
EROR TWITTER DOWNLOADER, TIKTOK DOWNLOADER

![image](https://user-images.githubusercontent.com/63404067/91968633-6f3ad480-ed04-11ea-86db-838e3073d2e3.png)
![image](https://user-images.githubusercontent.com/63404067/91968663-7b269680-ed04-11ea-80db-44ca3edc9923.png)

**Comment by rebahanelite** [comment]
Punyalu kali yang error, gw make normal" ajaa
![image](https://user-images.githubusercontent.com/68410598/91987886-ce2a3900-ed58-11ea-9a43-6722f06a1c0a.png)

**Comment by YogaSakti** [comment]
Linux Fix: https://trakteer.id/red-emperor/showcase/fix-whatsapp-bot-sticker-creator-di-c9-lpwel
