### ISSUE TITLE
Install di Heroku?

### ISSUE THREAD

**Issue by aidilaryanto** [YogaSakti/imageToSticker#42]
Bang, mo nanya. Ini bisa run di Heroku gak?

**Comment by daenghunter** [comment]
waahhh mster bot telegram disini...

**Comment by YogaSakti** [comment]
Bisa harusnya, tapi gak recom soalnya kan ini api wraper nya pake headless yang dari open-wa itu.

**Comment by YogaSakti** [comment]
saran sih mending pake [whatsapp-web.js](https://github.com/pedroslopez/whatsapp-web.js) kalo mau deploy ke heroku, tapi kalo mau deploy pake docker bisa aja pake open-wa

**Comment by kacang123** [comment]
nanti pakai whatsapp-web.js trus gimana bang ?
