### ISSUE TITLE
Ig downloader

### ISSUE THREAD

**Issue by Gimenz** [YogaSakti/imageToSticker#44]
bang gw nyoba bikin ig downloader pake module instagram-save 
bisa download foto/video

codingan gw gini, 

```
        case 'ig':
            if (args.length == 1) {
            client.sendText(from, '*Sedang memproses...*')
            const url = args[0]
            save(`${url}`, './save').then(res => {
                const hasil = (res.file)
                client.sendFile(from, hasil)
            });
            }
            break
```

**Comment by fnbots-wa** [comment]
hasilnya??

**Comment by Gimenz** [comment]
> hasilnya??

work, tapi pakai metode kirim file, bukan url

**Comment by YogaSakti** [comment]
outputnya gabisa url aja? biar gausah nyimpen file.

**Comment by fnbots-wa** [comment]
> > hasilnya??
> 
> work, tapi pakai metode kirim file, bukan url

oke dicoba gan.

**Comment by Gimenz** [comment]
> outputnya gabisa url aja? biar gausah nyimpen file.

coba kembangin a, barangkali bisa pake url

**Comment by fnbots-wa** [comment]
> outputnya gabisa url aja? biar gausah nyimpen file.

pake method
get
download
send
delete

aja gan...
ribet sih. ada limit bw juga. walaupun ada suka agak bermasalah di delay send media nya

**Comment by YogaSakti** [comment]
ig downloader udah fix ya di update terbaru

**Comment by Gimenz** [comment]
jos pokoke
