### ISSUE TITLE
repl.it Not working

### ISSUE THREAD

**Issue by kacang123** [YogaSakti/imageToSticker#48]

**Comment by YogaSakti** [comment]
udah ketebak wkwkwk,

**Comment by YogaSakti** [comment]
@benirabbny have you tried it on repl.it before?

**Comment by kacang123** [comment]
saya udah coba eh gagal output nya browser apa gitu lupa

**Comment by benirabbny** [comment]
Hmm sata juga sih ini saya pake cmd

**Comment by YogaSakti** [comment]
Screenshot errornya @kacang123 @benirabbny

**Comment by benirabbny** [comment]
Erorr To Load Browser, tolong Kalo Punya solusi Bro

Pada tanggal Sel, 8 Sep 2020 pukul 20.08 Imperial Owl <
notifications@github.com> menulis:

**Comment by benirabbny** [comment]
Erorr To Load Browser tulisannya, tolong kalo ada solusi @YogaSakti 
![image](https://user-images.githubusercontent.com/68042984/92481968-47220880-f211-11ea-8f29-4811dc8d6f81.png)

**Comment by YogaSakti** [comment]
Repl.it ada terminalnya gak?

**Comment by benirabbny** [comment]
ya itu terminal  bro

**Comment by kacang123** [comment]
saya pengen install google chrome pas sudo dpkg eh malah gk ada sudo

**Comment by mazrizal-id** [comment]
![Screenshot (209)](https://user-images.githubusercontent.com/70305920/92676845-a5073b00-f34c-11ea-8ec6-1c0174455fde.png)
work

**Comment by benirabbny** [comment]
Caranya gimana brow ?

**Comment by benirabbny** [comment]
bisa jalan ga bro? @mazrizal-id

**Comment by benirabbny** [comment]
![image](https://user-images.githubusercontent.com/68042984/92679049-953e2580-f351-11ea-9a9f-f89107d3f5c9.png)
kok saya kayak gini ya

**Comment by benirabbny** [comment]
saya pake yang terbaru ga bisa jalan
