### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Eroo768** [YogaSakti/imageToSticker#49]
Kenapa code qr nya gak muncul ya?bagaimana cara atasinya

**Comment by Eroo768** [comment]
![Screenshot_2020-09-08-21-51-42-68_fb47b6c93b99596be3e79670c6246005](https://user-images.githubusercontent.com/70959670/92496022-cd464b00-f221-11ea-9f6c-9bc2ef188a17.jpg)
Kek gni

**Comment by rebahanelite** [comment]
Coba (x86) di "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe" (util/option.js) nya hapus bang

**Comment by YogaSakti** [comment]
Install google chrome belom @Eroo768 ?

**Comment by btenay4** [comment]
google chrome belum ke instal itu.

**Comment by Eroo768** [comment]
![Screenshot_2020-09-09-04-15-38-79_fb47b6c93b99596be3e79670c6246005](https://user-images.githubusercontent.com/70959670/92528549-2b3f5680-f253-11ea-87da-9efc48909fcf.jpg)
Tetep aja bg

**Comment by kacang123** [comment]
udh install git ?
sama node js ?

**Comment by Eroo768** [comment]
Udah

**Comment by mazrizal-id** [comment]
Google Chrome nya ga ke detek itu mas
