### ISSUE TITLE
Cara Jalanin Bot Di Vps gmn ya

### ISSUE THREAD

**Issue by Eroo768** [YogaSakti/imageToSticker#52]
![Screenshot_2020-09-10-07-04-21-48](https://user-images.githubusercontent.com/70959670/92666619-f35c1000-f333-11ea-8c7e-dcc1d7759318.jpg)
Ni vps nya

**Comment by fnbots-wa** [comment]
apt update -y
apt upgrade -y
apt install nodejs -y
apt install git -y
git clone https://github.com/YogaSakti/imageToSticker
cd ImageToSticker
npm install
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo apt install ./google-chrome-stable_current_amd64.deb
npm start

**Comment by kacang123** [comment]
kalo gagal install google-chrome tinggal sudo apt-get -f install
