### ISSUE TITLE
QR code tidak muncul

### ISSUE THREAD

**Issue by dzakijo1** [YogaSakti/imageToSticker#53]
![image](https://user-images.githubusercontent.com/47619660/92691973-b1e85680-f36d-11ea-93b5-9391126599ea.png)

npm i terus npm start ceket disini bang, kenapa ya kira kira?

**Comment by YogaSakti** [comment]
buka file option.js didalem folder util terus hapus  (x86) jadi kayak dibawah ini
![image](https://user-images.githubusercontent.com/24309806/92692746-cda02c80-f36e-11ea-8872-8d7aa21c5076.png)

**Comment by dzakijo1** [comment]
udah di samain bang, tapi kadang masih bengong disitu, sempet muncul terus ane stop, npm start lagi bengong lagi

**Comment by YogaSakti** [comment]
Cek path google chromenya, terus samain di dalem file option itu

**Comment by dzakijo1** [comment]
udah sama destination foldernya, cuma sering bengong aja um..

**Comment by fnbots-wa** [comment]
pake rdp?

**Comment by dzakijo1** [comment]
udah fix sih ini, tapi pas saya coba pakai RDP ig downloadernya error

**Comment by YogaSakti** [comment]
#50
