### ISSUE TITLE
QR SCAN TOOK TOO LONG

### ISSUE THREAD

**Issue by MFarelSyahtiawan** [YogaSakti/imageToSticker#56]
Ini gimana ya bang, abis npm start, kan muncul qr nah padahal saya udah scan,tapi abis scan malah muncul tulisan gini

× QR scan took too long. Session Timed Out. Shutting down. Consider increasing qrTimeout config variable: https://open-wa.github.io/wa-automate-nodejs/interfaces/configobject.html#qrtimeout

**Comment by YogaSakti** [comment]
problem di koneksimu

**Comment by MFarelSyahtiawan** [comment]
> problem di koneksimu

Wifi kenceng bang
