### ISSUE TITLE
mention all sometimes not work

### ISSUE THREAD

**Issue by farrasrayhand** [YogaSakti/imageToSticker#57]
![image](https://user-images.githubusercontent.com/35839373/93272953-46790b80-f7e9-11ea-9eac-93ad0315eddf.png)
![image](https://user-images.githubusercontent.com/35839373/93273064-86d88980-f7e9-11ea-8337-937242a14b09.png)

**Comment by fnbots-wa** [comment]
dari modulnya memang yang agak delay, kadang muncul kadang nggak respon meskipun nggak ada error. coba aja command sendFile lalu tag atau reply, pasti delay. 
dari sendFile, sendImageAsSticker, sendTextWithMentions, reply. harus antri yang mana perintah yang lebih dulu harus diselesaikan dulu, makanya kadang bengong dan gada errornya. malah sampe sampe bengong terus kalo numpuk²

**Comment by YogaSakti** [comment]
yang bawah itu didalam grup yang kamu baru pertama kali masuk? atau belom ada interaksi dari orang didalam grup?

**Comment by farrasrayhand** [comment]
> yang bawah itu didalam grup yang kamu baru pertama kali masuk? atau belom ada interaksi dari orang didalam grup?

Udah lama sih, itu kayak gitu kadang"

**Comment by YogaSakti** [comment]
itu problem di wanya, bukan di scnya sih
