### ISSUE TITLE
error when run first time on ubuntu 18.04. some help?

### ISSUE THREAD

**Issue by erickythierry** [YogaSakti/imageToSticker#59]
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module './options'
Require stack:
- /root/Desktop/novo/imageToSticker/util/index.js
- /root/Desktop/novo/imageToSticker/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/root/Desktop/novo/imageToSticker/util/index.js:6:19)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/Desktop/novo/imageToSticker/util/index.js',
    '/root/Desktop/novo/imageToSticker/index.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! whatsapp-bot-sticker-creator@10.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the whatsapp-bot-sticker-creator@10.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-09-16T12_10_54_403Z-debug.log

**Comment by fnbots-wa** [comment]
try this again
```
git clone https://github.com/YogaSakti/imageToSticker/
```

**Comment by BASEBTM** [comment]
> internal/modules/cjs/loader.js:968
> throw err;
> ^
> 
> Error: Cannot find module './options'
> Require stack:
> 
> * /root/Desktop/novo/imageToSticker/util/index.js
> * /root/Desktop/novo/imageToSticker/index.js
>   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
>   at Function.Module._load (internal/modules/cjs/loader.js:841:27)
>   at Module.require (internal/modules/cjs/loader.js:1025:19)
>   at require (internal/modules/cjs/helpers.js:72:18)
>   at Object. (/root/Desktop/novo/imageToSticker/util/index.js:6:19)
>   at Module._compile (internal/modules/cjs/loader.js:1137:30)
>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
>   at Module.load (internal/modules/cjs/loader.js:985:32)
>   at Function.Module._load (internal/modules/cjs/loader.js:878:14)
>   at Module.require (internal/modules/cjs/loader.js:1025:19) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>   '/root/Desktop/novo/imageToSticker/util/index.js',
>   '/root/Desktop/novo/imageToSticker/index.js'
>   ]
>   }
>   npm ERR! code ELIFECYCLE
>   npm ERR! errno 1
>   npm ERR! whatsapp-bot-sticker-creator@10.0.0 start: `node index.js`
>   npm ERR! Exit status 1
>   npm ERR!
>   npm ERR! Failed at the whatsapp-bot-sticker-creator@10.0.0 start script.
>   npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! /root/.npm/_logs/2020-09-16T12_10_54_403Z-debug.log

Me too

**Comment by YogaSakti** [comment]
sorry, i made a mistake. I'll fix it in a moment

**Comment by YogaSakti** [comment]
I've fixed it, please try it

**Comment by BASEBTM** [comment]
> I've fixed it, please try it @BASEBTM @erickythierry

Thank you so much for the fixed. It Works.

**Comment by erickythierry** [comment]
> I've fixed it, please try it @BASEBTM @erickythierry

Thank you so much. now working
