### ISSUE TITLE
#tiktok command error

### ISSUE THREAD

**Issue by ppabcd** [YogaSakti/imageToSticker#6]
`Caught exception:  Error: Evaluation failed: Error: InvalidMediaFileType: ExtendableError
    at t.value [as sendToChat] (https://web.whatsapp.com/app2.bd99e00dba1790b9096f.js:2:423105)
    at /home/test/node_modules/@open-wa/wa-automate/dist/lib/wapi.js:1536:25
    at async /home/test/node_modules/@open-wa/wa-automate/dist/lib/wapi.js:1533:16
    at ExecutionContext._evaluateInternal (/home/test/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

**Comment by YogaSakti** [comment]
install google-chrome and add executable path in index file

**Comment by ppabcd** [comment]
I use this code
```
const serverOption = {
    headless: true,
    qrRefreshS: 20,
    qrTimeout: 0,
    authTimeout: 0,
    autoRefresh: true,
    devtools: false,
    cacheEnabled: false,
    chromiumArgs: [
        '--no-sandbox',
        '--disable-setuid-sandbox'
    ]
}

const opsys = process.platform;
if (opsys == "win32" || opsys == "win64") {
    serverOption['executablePath'] = 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe';
} else if (opsys == "linux") {
    serverOption['browserRevision'] = '/usr/bin/google-chrome';
} else if (opsys == "darwin") {
    serverOption['executablePath'] = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
}
```
but still doesn't work. For installation, i use this chrome.
```
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
```
