### ISSUE TITLE
pass npm i eror kak waktu yang versi awal lancar2 aja

### ISSUE THREAD

**Issue by ilham1104** [YogaSakti/imageToSticker#62]
C:\Users\ztsu>cd imageToSticker

C:\Users\ztsu\imageToSticker>npm i
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm ERR! Unexpected end of JSON input while parsing near '...https://openpgpjs.org'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ztsu\AppData\Roaming\npm-cache\_logs\2020-09-18T04_39_33_529Z-debug.log

**Comment by ilham1104** [comment]
klo bisa saya minta wa dong kak

**Comment by YogaSakti** [comment]
```
npm cache clean --force
```
terus 
```
npm install
```

**Comment by ilham1104** [comment]
makasih kak udah fix
