### ISSUE TITLE
TUTORIAL

### ISSUE THREAD

**Issue by ben-dev2609** [YogaSakti/imageToSticker#64]
Bang cara update nya itu gimana?

**Comment by nikkixploit** [comment]
> Bang cara update nya itu gimana?

`git pull`

**Comment by ben-dev2609** [comment]
> > Bang cara update nya itu gimana?
> 
> `git pull`

itu git pull nya ditulis dimana nya bang

**Comment by ben-dev2609** [comment]
![Screenshot (27)](https://user-images.githubusercontent.com/70950474/93774459-7d1caf00-fc4b-11ea-9d5a-ac59a2368d3d.png)
kalau ini gimana bang
