### ISSUE TITLE
ini bukan isu sih cuman minta req

### ISSUE THREAD

**Issue by ilham1104** [YogaSakti/imageToSticker#66]
Tambahin cari lirik lagu bang sama yt to mp3 makasih kak

**Comment by rebahanelite** [comment]
kalo lirik lagu pake aja api terhampar, kalo yt mp3 pake aja api yutube.herokuapp.com

**Comment by ben-dev2609** [comment]
> kalo lirik lagu pake aja api terhampar, kalo yt mp3 pake aja api yutube.herokuapp.com

maksudnya apa bang

**Comment by ilham1104** [comment]
> kalo lirik lagu pake aja api terhampar, kalo yt mp3 pake aja api yutube.herokuapp.com

makasih saya coba dulu, walau gak paham node js wkwkwk

**Comment by ben-dev2609** [comment]
bisa dijelasin ga bang?

**Comment by btenay4** [comment]
> 
> 
> kalo lirik lagu pake aja api terhampar, kalo yt mp3 pake aja api yutube.herokuapp.com

api terhambar documentationnya apa ya ?

**Comment by rebahanelite** [comment]
> bisa dijelasin ga bang?
pake api bang

**Comment by rebahanelite** [comment]
> > kalo lirik lagu pake aja api terhampar, kalo yt mp3 pake aja api yutube.herokuapp.com
> 
> api terhambar documentationnya apa ya ?

https://documenter.getpostman.com/view/10780576/T1Ds9bRV?version=latest

**Comment by btenay4** [comment]
> 
> 
> Tambahin cari lirik lagu bang sama yt to mp3 makasih kak

case'ytmp3':
            if (args.length !== 1) return client.reply(from, 'Maaf, format pesan salah silahkan', id)
            client.reply(from, '_Scraping Metadata..._ ', message.id)
            axios.get('http://scrap.terhambar.com/yt?link='+ args[0])
            .then(function(response){
                if(response.data.status == false){
                    client.reply(from, 'Maaf _Link_ Tidak valid', from)
                }
                else{
                    client.sendFileFromUrl(from, response.data.linkAudioOnly, response.data.title+'.mp3',null, null, true)
                }
            })
            .catch(function(error){
                console.log(error)
            })
            break

**Comment by YogaSakti** [comment]
terhambar mati apinya

**Comment by ben-dev2609** [comment]
> > bisa dijelasin ga bang?
> > pake api bang

maksudnya apa bang? bisa dijelasin lebih detail nya ga bang?

**Comment by rebahanelite** [comment]
> > > bisa dijelasin ga bang?
> > > pake api bang
> 
> maksudnya apa bang? bisa dijelasin lebih detail nya ga bang?
send file from url dari api bang, ato pake ytdl-core

**Comment by ben-dev2609** [comment]
tetap ga paham wkwk
