### ISSUE TITLE
how to install in rdp?

### ISSUE THREAD

**Issue by arh-space** [YogaSakti/imageToSticker#67]

**Comment by arh-space** [comment]
Error: Failed to launch the browser proccess! spawn C:\ProgramFiles <x86> \GoogleChrome\Chrome\Application\chrome.exe EONENT!

**Comment by nikkixploit** [comment]
> Error: Failed to launch the browser proccess! spawn C:\ProgramFiles \GoogleChrome\Chrome\Application\chrome.exe EONENT!

Udah install chrome belum?

**Comment by YogaSakti** [comment]
install google chrome
