### ISSUE TITLE
Media Dowloader Not Working

### ISSUE THREAD

**Issue by aidilaryanto** [YogaSakti/imageToSticker#68]
![Uploading Screenshot_20200922-101050656.jpg…]()
 Twitter, IG downloader not work.

**Comment by YogaSakti** [comment]
ig work, servermu kena blok sama ig, twitter limit api

**Comment by aidilaryanto** [comment]
"Error, user private atau link salah [Private or Invalid Link]" kayak gitu bang. Ini kena block yak?

**Comment by aidilaryanto** [comment]
Aku deploy di Heroku sih

**Comment by YogaSakti** [comment]
cek log nya di terminal

**Comment by aidilaryanto** [comment]
> cek log nya di terminal

![Uploading Screenshot_20200924-083852054.jpg…]()
