### ISSUE TITLE
Meme is not working anymore

### ISSUE THREAD

**Issue by Danzi3103** [YogaSakti/imageToSticker#69]
After the bot update i get only an Error the format is wrong message. before the update he sends everytime an meme after i write #Meme. Is there now a different command for memes out of random subreddits?

**Comment by Danzi3103** [comment]
![Unbenannt](https://user-images.githubusercontent.com/70868903/94034905-ce9b7a00-fdc2-11ea-8e54-8190c0381caf.png)

**Comment by SlavyanDesu** [comment]
Add this command:
```js
case 'reddit':
  meme.random()
    .then(({ subreddit, title, url }) => {
      client.sendFileFromUrl(from, `${url}`, 'meme.jpg', `${title}\nTag: r/${subreddit}`, null, null, true)
    })
    .catch((err) => console.error(err))
break
```
The `#meme` command you are using is for adding meme text to a sended picture. For more details, see `#help`.

**Comment by SlavyanDesu** [comment]
@YogaSakti bisa di close pak?

**Comment by farrasrayhand** [comment]
udah beda fungsinya, sekarang jadi perintah buat edit foto jadi meme

**Comment by SlavyanDesu** [comment]
> udah beda fungsinya, sekarang jadi perintah buat edit foto jadi meme

Ho'oh
