### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by MrPawNO** [YogaSakti/imageToSticker#7]
npm start

> whatsapp-bot-sticker-creator@4.1.0 start /data/data/com.termux/files/home/imageToSticker
> node index.js

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! whatsapp-bot-sticker-creator@4.1.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the whatsapp-bot-sticker-creator@4.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2020-07-31T11_26_09_762Z-debug.log

**Comment by YogaSakti** [comment]
error gak lengkap, gabisa di liat itu error apa

**Comment by daenghunter** [comment]
eh bentar, kok termux?
