### ISSUE TITLE
the session invalid

### ISSUE THREAD

**Issue by kazuRW** [YogaSakti/imageToSticker#70]
![image](https://user-images.githubusercontent.com/67783779/94090270-63dc5400-fe3f-11ea-91b2-11cd9c10e134.png)

**Comment by rebahanelite** [comment]
Sama bang, kenapa yak

**Comment by fadhil050804** [comment]
sama gw juga bang

**Comment by NaldoMota1** [comment]
Tampaknya setiap orang memiliki masalah yang sama

**Comment by aidilaryanto** [comment]
Sama. Kayaknya masalah di open-wa

**Comment by fadhil050804** [comment]
> Sama. Kayaknya masalah di open-wa

sekarang malah bengong

**Comment by fadhil050804** [comment]
gak muncul qr code nya

**Comment by fadlurhmn** [comment]
sama

**Comment by SlavyanDesu** [comment]
Sama gw juga kek gini habis ngeauth
```bash
(node:3744) UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
    at CDPSession.send (C:\Users\Heikal Syah Shiddiq\imageToSticker-master\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:195:35)  
    at ExecutionContext._evaluateInternal (C:\Users\Heikal Syah Shiddiq\imageToSticker-master\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:200:50)
    at ExecutionContext.evaluate (C:\Users\Heikal Syah Shiddiq\imageToSticker-master\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:27)
    at DOMWorld.evaluate (C:\Users\Heikal Syah Shiddiq\imageToSticker-master\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:79:24)   
(node:3744) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, 
use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:3744) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Keknya dari wa-automate nya
![image](https://user-images.githubusercontent.com/28254882/94093697-0d274800-fe48-11ea-85ee-706deaef2986.png)

**Comment by EthanNoSkill** [comment]
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ █▀█▄▄▄▄ ▄▄▀█ ▄▄▀██  ▀▄█  ▄ █▀▄█ ▄▄▄▄▄ █
█ █   █ █▄▀█▀ █▄█ ▄██ ▀  ██▄▄█ ▀▄███ ▀█ █   █ █
█ █▄▄▄█ █ ██   ▄▄▀ █  ▄▄▄ ▀▄▄▄▀ ▀▄ ▄▄▄█ █▄▄▄█ █
█▄▄▄▄▄▄▄█ ▀ █▄█▄▀ █▄█ █▄█ █▄█ ▀▄█▄█ ▀▄█▄▄▄▄▄▄▄█
█ ▄█▄▀█▄▄▀█ █▀▄████▄▄▄  ▄ ▄▄  ▄█▄▀▄█▀██▄▄▄█ ▄▀█
█ █▀▀█▄▄▄  █▀▀▄█▀▀ ▄█▀▄▄▀ ▀▄▄▄█▄ ▀▀▄▄█▄▀▄ ▄▄▀ █
█▄█▀ █ ▄▀▀▄   ▀ ▄▀▄▄ ▀█▄▄▄ █▄ █▄  ▄ █▄▀▄ ▄ █▀▀█
█▄ █▄▀▀▄█▄  ▀█▄█ ▄▄  ▄█▄▀▄█▄▀▄█▄▀▀▄▀▄██▀▀██████
█▀▀ ▀█▀▄▀ █▄▀▄█▄▄█▄ ▄▀▀▄▄ █▀ █▄█▀▄██▄█▀▀▄█▀▀▄▄█
█▄▄▀█▀▀▄ █▄▄▀▀▄▄  ▀▄▀▄ ▀ ▄▀ █▄▄█ ▄▀▀▀▀ ▀█▀ ▄█▄█
█▀ ▀▀ ▄▄▄ ▄▀▄█ ▀█▄█▄▀ ▄▄▄ █▄▀ █▄▄█▄▄█ ▄▄▄ ▄█▀██
██  ▄ █▄█ ▄█▀▀ ▀ ▄█▀  █▄█ ▀▄█ ██▄ █▀█ █▄█ ▀▄█ █
██ ▄   ▄ ▄▀  ▄  ▄▀   ▄ ▄  ▀▄▄▄▄▄▄ █▀▄ ▄▄▄ █▀█▄█
█▀▄▄██▄▄ ▀▀▄▀▄████▀▄█▀▀▀▀█▀ ▄█▀▀   ▀▄▀█▀█▀▄▄▄██
██▀ ▄▄▄▄█ ▄█ ▄▀ ██▄ ██▄██▄▄▀ █ ▄▀▄████▀ ▄▄▀█  █
█▀█▀  ▀▄█ ▄▄▄▄  █ ███ ███▄▀▀▀██▄▄▄█ █   ▄ ▄█ ▄█
██  ▄▄ ▄▀█▄ ▄ █▀██▀▄█▀▄▄█▄██▀▄▄▄ ██▄ ▀▄███ ▀█ █
██▀▀▀ █▄██  ▀▀▄▀ ▄▄  ▀▀▄▄██ ▄████  ▀█▀▄▄▄ ██  █
█▄██▄▄█▄▄▀▀ ▄▄▄ ▄   ▀ ▄▄▄ ██▄▄▄▄▄ █▀█ ▄▄▄ █████
█ ▄▄▄▄▄ █▄▀▄▀█▄▄▄▄▄▀█ █▄█   ▄ ██▀ ▀█  █▄█ █▄▄██
█ █   █ █▀█▄█▄▄▄▄█▀  ▄▄▄ ▄▄▀▄█▀▄▀▄▄█▀ ▄  ▄▄ ▄ █
█ █▄▄▄█ █▀█▄▄ ▄▄ ▄▄▀█▀█  ▄█▀█▀▀█▀████ ▀▄▄▄ ████
█▄▄▄▄▄▄▄█▄▄▄█████▄█▄▄████▄██▄▄█▄▄█▄▄█▄▄▄▄▄▄█▄██

**Comment by ben-dev2609** [comment]
sama bro gw juga gitu

**Comment by YogaSakti** [comment]
Halo ini bug di open-wa ya jadi tunggu bug fix dari library nya dulu

**Comment by fadhil050804** [comment]
> Halo ini bug di open-wa ya jadi tunggu bug fix dari library nya dulu

ok bang. tambahin fitur bang. yt mp3, yt downloader, tik tok, sticker no bg, dll bang. biar mantep

**Comment by YogaSakti** [comment]
> > Halo ini bug di open-wa ya jadi tunggu bug fix dari library nya dulu
> 
> ok bang. tambahin fitur bang. yt mp3, yt downloader, tik tok, sticker no bg, dll bang. biar mantep

tiktok udah ada, sticker no bg udah ada di [trakteer](https://trakteer.id/red-emperor/showcase/mention-all-whatsapp-bot-feature-9EVf0)

**Comment by shansekai** [comment]
Yang males nunggu fix dari open-wa coba pake cara ini.

Copy semua text ini : [https://raw.githubusercontent.com/open-wa/wa-automate-nodejs/f4cc51423aa367ad3c7b735a799d6f7d6ab05051/src/lib/wapi.js](https://raw.githubusercontent.com/open-wa/wa-automate-nodejs/f4cc51423aa367ad3c7b735a799d6f7d6ab05051/src/lib/wapi.js)  Terus masuk ke folder : `@open-wa => wa-automate => dist => lib => wapi.js`  dan replace yang text lu copy tadi.

**Comment by ben-dev2609** [comment]
> ./node_modules/@open-wa/wa-automate/dist/lib/wapi.js
@Terror-Machine maksudnya apa bang bisa dijelasin lebih simple?

**Comment by btenay4** [comment]
> 
> 
> ```
> https://raw.githubusercontent.com/open-wa/wa-automate-nodejs/f4cc51423aa367ad3c7b735a799d6f7d6ab05051/src/lib/wapi.js
> ```
> 
> buka link ini dan copy semua isinya
> dan replace ke sini
> 
> ```
> ./node_modules/@open-wa/wa-automate/dist/lib/wapi.js
> ```
> 
> atau kalo mau nunggu update resminya dari @open-wa/wa-automate-nodejs

pro emang stah satu ini

**Comment by ben-dev2609** [comment]
wah tetap ga paham wkwk

kalau yg di nodejs sama aja?

**Comment by btenay4** [comment]
> 
> 
> wah tetap ga paham wkwk
> 
> kalau yg di nodejs sama aja?

tunggu update resminya aja bang

**Comment by ben-dev2609** [comment]
> > wah tetap ga paham wkwk
> > kalau yg di nodejs sama aja?
> 
> tunggu update resminya aja bang

ow ok makasih infonya bang

**Comment by aidilaryanto** [comment]
> ```
> https://raw.githubusercontent.com/open-wa/wa-automate-nodejs/f4cc51423aa367ad3c7b735a799d6f7d6ab05051/src/lib/wapi.js
> ```
> 
> buka link ini dan copy semua isinya
> dan replace ke sini
> 
> ```
> ./node_modules/@open-wa/wa-automate/dist/lib/wapi.js
> ```
> 
> atau kalo mau nunggu update resminya dari @open-wa/wa-automate-nodejs

fixed pake ini. Thankyouu

**Comment by YogaSakti** [comment]
Itu udah update, gausah edit wapi segala

**Comment by aidilaryanto** [comment]
> Itu udah update, gausah edit wapi segala

Iyaa barusan cek. eh dah update

**Comment by NaldoMota1** [comment]
kapan akan diperbaiki?

**Comment by NaldoMota1** [comment]
> kapan akan diperbaiki?

bagaimana cara memperbarui?

**Comment by SlavyanDesu** [comment]
> > kapan akan diperbaiki?
> 
> bagaimana cara memperbarui?

```bash
> npm update
```

**Comment by NaldoMota1** [comment]
selalu memberikan sesi tidak valid.

**Comment by SlavyanDesu** [comment]
> selalu memberikan sesi tidak valid.

Hmm, coba hapus `session.data.json` lalu coba scan QR lagi. Pastikan versi module `@open-wa/wa-automate` berada di versi 2.0.25

**Comment by YogaSakti** [comment]
ok bug ini udah fix ya, kututup issuenya
