### ISSUE TITLE
Cannot authenticate

### ISSUE THREAD

**Issue by F0oa** [YogaSakti/imageToSticker#71]
Knapa gini terus, pdhl udah scan qr dan berhasil.
Kadang juga gaada tulisan merah tapi loading qr lagi
![Screenshot_20200924-110043](https://user-images.githubusercontent.com/71806804/94099842-17e8d980-fe56-11ea-84d3-c4e941e7abe9.jpg)

**Comment by YogaSakti** [comment]
Duplicate #70

**Comment by F0oa** [comment]
Duplicate gimana bg?
