### ISSUE TITLE
npm i can't

### ISSUE THREAD

**Issue by arh-space** [YogaSakti/imageToSticker#73]
![1](https://user-images.githubusercontent.com/65483182/94163630-46949d80-feb2-11ea-8f82-c9128dd77c77.jpg)

can't install

**Comment by SlavyanDesu** [comment]
Udah install git kah?

**Comment by YogaSakti** [comment]
install git dulu

**Comment by arh-space** [comment]
solved thanks :+1:

**Comment by TentacleSama4254** [comment]
lost

**Comment by SlavyanDesu** [comment]
Wut
