### ISSUE TITLE
stuck di rdp windows server 2012

### ISSUE THREAD

**Issue by benirabbny** [YogaSakti/imageToSticker#77]
![image](https://user-images.githubusercontent.com/68042984/94363859-5e0c9a00-00ef-11eb-88ec-23ae1e1c1323.png)
kok berhenti disini kenapa ya ?

**Comment by SlavyanDesu** [comment]
> ![image](https://user-images.githubusercontent.com/68042984/94363859-5e0c9a00-00ef-11eb-88ec-23ae1e1c1323.png)
> kok berhenti disini kenapa ya ?

install chrome dulu

**Comment by ben-dev2609** [comment]
![Uploading Screenshot (31).png…]()

**Comment by ben-dev2609** [comment]
![Screenshot (31)](https://user-images.githubusercontent.com/70950474/94382541-496be880-0167-11eb-9fc9-47b613b15556.png)

**Comment by fdciabdul** [comment]
> ![Screenshot (31)](https://user-images.githubusercontent.com/70950474/94382541-496be880-0167-11eb-9fc9-47b613b15556.png)
> 
> kok saya stuck disin?
> i

ketik `npm update` buat update library ke ke versi terbaru

**Comment by YogaSakti** [comment]
stuck auth tuh masalah RDPmu

**Comment by prodas123** [comment]
> stuck auth tuh masalah RDPmu

trs cara fix ny gmn kak ?

**Comment by ben-dev2609** [comment]
> > ![Screenshot (31)](https://user-images.githubusercontent.com/70950474/94382541-496be880-0167-11eb-9fc9-47b613b15556.png)
> > kok saya stuck disin?
> > i
> 
> ketik `npm update` buat update library ke ke versi terbaru

tetap sama aja kalau `npm update`

**Comment by YogaSakti** [comment]
itu udah masuk auth itu udah bisa, tunggu aja

kalo lama di authenticating itu masalah di koneksi ke server WAnya ya
