### ISSUE TITLE
Mau Nanya Bang

### ISSUE THREAD

**Issue by lixorhaxz** [YogaSakti/imageToSticker#78]
Botnya bisa nyala gak kalo hp di matiin?

**Comment by Gimenz** [comment]
> Botnya bisa nyala gak kalo hp di matiin?

gk bisa

**Comment by prodas123** [comment]
trs cr biar aktifin trs gmn ?/

**Comment by CuekGaming** [comment]
keknya pake emulator deh trus daftar WhatsApp di situ, maybe?

**Comment by fdciabdul** [comment]
> keknya pake emulator deh trus daftar WhatsApp di situ, maybe?

gabisa pake emulator juga

**Comment by prodas123** [comment]
deploy ke heroku gmn caranya y ? biar botny bs aktif 24 jam

**Comment by fdciabdul** [comment]
> deploy ke heroku gmn caranya y ? biar botny bs aktif 24 jam

gabisa ke heroku , soalnya gabisa seting path chromium nya

pake rdp / vps

**Comment by YogaSakti** [comment]
gabisa ya, hp harus aktif

**Comment by prodas123** [comment]
oalah , yah ga bisa stay 24 jam ;'v , tpi gpp ini udh bagus bgt

**Comment by YogaSakti** [comment]
Pake cloud emulator sih kalo mau, sekitar $9an perbulan

**Comment by fdciabdul** [comment]
> Pake cloud emulator sih kalo mau, sekitar $9an perbulan

tetep aja kan scan qr nya itu lho

**Comment by YogaSakti** [comment]
> > Pake cloud emulator sih kalo mau, sekitar $9an perbulan
> 
> tetep aja kan scan qr nya itu lho

Tinggal di scan kan wkwkwk

**Comment by fdciabdul** [comment]
> > > Pake cloud emulator sih kalo mau, sekitar $9an perbulan
> > 
> > 
> > tetep aja kan scan qr nya itu lho
> 
> Tinggal di scan kan wkwkwk

gimana cara scan nya di emulator euy , pake recorder screen atau fake camera ?
soalnya perlu webcam juga kalo buat ngescan nya

masih nyari cara sih buat scan qr di whatsapp tanpa open camera / scan langsung di layarnya

**Comment by prodas123** [comment]
> > > > Pake cloud emulator sih kalo mau, sekitar $9an perbulan
> > > 
> > > 
> > > tetep aja kan scan qr nya itu lho
> > 
> > 
> > Tinggal di scan kan wkwkwk
> 
> gimana cara scan nya di emulator euy , pake recorder screen atau fake camera ?
> soalnya perlu webcam juga kalo buat ngescan nya
> 
> masih nyari cara sih buat scan qr di whatsapp tanpa open camera / scan langsung di layarnya

tdi ku nnton vidio mu di yt ;'v yg tutor bot termux trnyt kau disini juga rupanya
