### ISSUE TITLE
bot not work?

### ISSUE THREAD

**Issue by farrasrayhand** [YogaSakti/imageToSticker#80]

**Comment by farrasrayhand** [comment]
![image](https://user-images.githubusercontent.com/35839373/94562671-31e04d00-0298-11eb-9a4d-79d2b88f805b.png)
![image](https://user-images.githubusercontent.com/35839373/94562710-3dcc0f00-0298-11eb-8285-f58fd8faabad.png)

**Comment by rebahanelite** [comment]
npm update

**Comment by farrasrayhand** [comment]
closed
