### ISSUE TITLE
Twitter & Tiktok downloader error

### ISSUE THREAD

**Issue by shansekai** [YogaSakti/imageToSticker#89]
Saya mau tanya, ini kenapa kok saya error ya?
Apa masalah di api nya?

Ini twitter
![20201007_222632](https://user-images.githubusercontent.com/34540627/95352545-87e26f80-08ec-11eb-992f-703c6f17d445.jpg)

Dan ini Tiktok
![20201007_222647](https://user-images.githubusercontent.com/34540627/95352262-45209780-08ec-11eb-8ade-c6dbeca8658b.jpg)

Terimakasih.

**Comment by YogaSakti** [comment]
Twitter API Limit
Tiktok url gak support

**Comment by shansekai** [comment]
> Twitter API Limit
> Tiktok url gak support

Ouh oke oke, di tunggu bang update terbarunya xixixi
