### ISSUE TITLE
Cara Dapetin Semua ARGS

### ISSUE THREAD

**Issue by AthallahDzaki** [YogaSakti/imageToSticker#98]
Ketika saya mengetik sebuah command dengan args lebih dari 1 maka semua args akan kebaca, tapi bagaimana caranya?
contoh 

#kalkulator 1 * 2 * 3 + 2 / 2

Nah argsnya kebaca semua, total 17 args kebaca (+ spasi karena args juga)

**Comment by rebahanelite** [comment]
#CMIIW
Kalo mau dapetin semua pake arg aja pak
Kalau mau pake urutan spesifik Pake args[urutan]

**Comment by Nurutomo** [comment]
```args.join(' ')```
Mungkin itu bisa

**Comment by AthallahDzaki** [comment]
Oke thanks gan Close Issues
